name: 'build'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["release-v5.1", "latest"]
        idf_target: ["esp32"]
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: esp-idf build monitor
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: ${{ matrix.idf_ver }}
          target: ${{ matrix.idf_target }}
          path: "examples/loconet-monitor"