name: 'build'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["release-v5.1", "latest"]
        idf_target: ["esp32"]
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Build for ${{ matrix.idf_target }}
        env:
            IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        working-directory: examples/loconet-monitor
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build